export type HzauCampusMapData = {
  meta: {
    generatedAt: string;
    source: string;
    campus: {
      relationId: number;
      name: string;
      nameEn: string;
      center: {
        latitude: number;
        longitude: number;
      };
      sourceTags: Record<string, string>;
    };
    outputPath: string;
  };
  stats: {
    raw: {
      namedBuildings: number;
      facilityCandidates: number;
      roadWays: number;
    };
    cleaned: {
      attractions: number;
      facilities: number;
      roadNodes: number;
      roadEdges: number;
    };
  };
  attractions: Array<{
    id: string;
    sourceType: 'node' | 'way' | 'relation';
    sourceId: number;
    name: string;
    category: string;
    latitude: number;
    longitude: number;
    tags: string[];
    sourceTags: Record<string, string>;
  }>;
  facilities: Array<{
    id: string;
    sourceType: 'node' | 'way' | 'relation';
    sourceId: number;
    name: string;
    category: string;
    latitude: number;
    longitude: number;
    tags: string[];
    sourceTags: Record<string, string>;
  }>;
  roadNetwork: {
    nodes: Array<{
      id: string;
      latitude: number;
      longitude: number;
      name: string;
      type: 'junction';
    }>;
    edges: Array<{
      id: string;
      fromNodeId: string;
      toNodeId: string;
      distance: number;
      roadType: 'main_road' | 'side_road' | 'bicycle_path' | 'footpath';
      allowedTransportation: string[];
      isElectricCartRoute: boolean;
      isBicyclePath: boolean;
      sourceWayId: number;
      sourceHighway: string;
      roadName: string;
    }>;
  };
};

// Generated by `npm run process-map:hzau`.
// eslint-disable-next-line @typescript-eslint/no-var-requires
export const HZAU_CAMPUS_MAP: HzauCampusMapData = require('./hzauCampusMap.json');
